FROM python:3.12-slim

WORKDIR /opt/project

RUN pip install --no-cache-dir \
    "setuptools<81" \
    "mlflow==2.14.1" \
    pandas \
    pyarrow \
    scikit-learn \
    xgboost

ENV PYTHONUNBUFFERED=1